from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Literal
from enum import Enum

class Tier(BaseModel):
    startingUnit: float
    endingUnit: Optional[float] = None
    price: float
    priceFormat: Literal["FlatFee", "PerUnit"] = "PerUnit"

class Charge(BaseModel):
    name: str
    type: Literal["Recurring", "OneTime", "Usage"]
    model: str = Field(..., description="Flat Fee Pricing, Per Unit Pricing, Volume Pricing, Tiered Pricing, Prepaid with Drawdown")
    billingPeriod: Optional[str] = None # Month, Quarter, Annual
    billingTiming: Optional[str] = "In Advance"
    uom: Optional[str] = None
    price: Optional[float] = None
    currency: str = "USD"
    includedUnits: Optional[float] = None
    overagePrice: Optional[float] = None
    tiers: Optional[List[Tier]] = None
    triggerEvent: str = "ContractEffective"
    # PWD specific
    prepaidLoadAmount: Optional[float] = None
    autoTopupThreshold: Optional[float] = None
    rolloverPct: Optional[float] = None
    rolloverCap: Optional[float] = None

class RatePlan(BaseModel):
    name: str
    description: Optional[str] = None
    charges: List[Charge] = []

class Product(BaseModel):
    name: str
    sku: str
    description: Optional[str] = None
    effectiveStartDate: str
    effectiveEndDate: Optional[str] = None
    ratePlans: List[RatePlan] = []

class ProductSpec(BaseModel):
    """
    The complete specification for creating a Product in Zuora.
    """
    product: Product
    comment: Optional[str] = "Generated by Zuora Seed Agent"


# ============ Chat API Models ============

class ZuoraApiType(str, Enum):
    """Commerce API types for Product Manager persona."""
    PRODUCT = "product"
    PRODUCT_RATE_PLAN = "product_rate_plan"
    PRODUCT_RATE_PLAN_CHARGE = "product_rate_plan_charge"
    PRODUCT_RATE_PLAN_CHARGE_TIER = "product_rate_plan_charge_tier"


class ZuoraApiPayload(BaseModel):
    """A single Zuora API payload with its type."""
    payload: Dict[str, Any] = Field(..., description="The actual payload data")
    zuora_api_type: ZuoraApiType = Field(..., description="Type of Zuora API this payload is for")
    payload_id: Optional[str] = Field(None, description="Optional ID to track this payload across requests")


class Citation(BaseModel):
    """Citation from knowledge base (mocked for now)."""
    id: str = Field(..., description="Unique identifier for this citation")
    title: str = Field(..., description="Title of the source document")
    uri: Optional[str] = Field(None, description="S3 URI of the source")
    url: Optional[str] = Field(None, description="HTTPS URL for the source")


class ChatRequest(BaseModel):
    """Request model for POST /chat endpoint."""
    persona: str = Field(..., description="User persona making the request (e.g., 'ProjectManager')")
    message: str = Field(..., description="User's message/question")
    conversation_id: Optional[str] = Field(None, description="Conversation ID for session continuity")
    zuora_api_payloads: List[ZuoraApiPayload] = Field(
        default_factory=list,
        description="List of Zuora API payloads for the agent to work with"
    )


class ChatResponse(BaseModel):
    """Response model for POST /chat endpoint."""
    conversation_id: str = Field(..., description="Conversation ID (new or existing)")
    answer: str = Field(..., description="Agent's response message")
    citations: List[Citation] = Field(
        default_factory=list,
        description="Citations from knowledge base (mocked)"
    )
    zuora_api_payloads: List[ZuoraApiPayload] = Field(
        default_factory=list,
        description="Modified/created Zuora API payloads"
    )
