from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Literal

class Tier(BaseModel):
    startingUnit: float
    endingUnit: Optional[float] = None
    price: float
    priceFormat: Literal["FlatFee", "PerUnit"] = "PerUnit"

class Charge(BaseModel):
    name: str
    type: Literal["Recurring", "OneTime", "Usage"]
    model: str = Field(..., description="Flat Fee Pricing, Per Unit Pricing, Volume Pricing, Tiered Pricing, Prepaid with Drawdown")
    billingPeriod: Optional[str] = None # Month, Quarter, Annual
    billingTiming: Optional[str] = "In Advance"
    uom: Optional[str] = None
    price: Optional[float] = None
    currency: str = "USD"
    includedUnits: Optional[float] = None
    overagePrice: Optional[float] = None
    tiers: Optional[List[Tier]] = None
    triggerEvent: str = "ContractEffective"
    # PWD specific
    prepaidLoadAmount: Optional[float] = None
    autoTopupThreshold: Optional[float] = None
    rolloverPct: Optional[float] = None
    rolloverCap: Optional[float] = None

class RatePlan(BaseModel):
    name: str
    description: Optional[str] = None
    charges: List[Charge] = []

class Product(BaseModel):
    name: str
    sku: str
    description: Optional[str] = None
    effectiveStartDate: str
    effectiveEndDate: Optional[str] = None
    ratePlans: List[RatePlan] = []

class ProductSpec(BaseModel):
    """
    The complete specification for creating a Product in Zuora.
    """
    product: Product
    comment: Optional[str] = "Generated by Zuora Seed Agent"
